runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)

- url: /public/css/(.*)
  static_files: \1
  upload: (.*)
  http_headers:
    Cache-control: max-age=31536000

- url: /public/js/(.*)
  static_files: \1
  upload: (.*)
  http_headers:
    Cache-control: private, max-age=31536000

- url: /public/img/(.*)
  static_files: \1
  upload: (.*)
  http_headers:
    Cache-control: max-age=86400

skip_files:
- node_modules/